### ISSUE TITLE
 named exports will cause Fast Refresh to not preserve local component state and do a full refresh

### ISSUE THREAD

**Issue by joshuacox** [kalwalt/gatsby-starter-i18n-bulma#142]
When doing a `gatsby develop` I get this warning:

```
warn 
/tmp/gatsby-starter-i18n-bulma/src/templates/blog-post.js
  10:1  warning  In page templates only a default export of a valid React component and the named export of a page
query is allowed.
        All other named exports will cause Fast Refresh to not preserve local component state and do a full refresh.

        Please move your other named exports to another file. Also make sure that you only export page queries that
use the "graphql" tag from "gatsby".
  limited-exports-page-templates
```

 I think this might be quite a performance hit:

https://www.gatsbyjs.com/docs/reference/local-development/fast-refresh/

I think this might be as simple as importing BlogPostTemplate from another file and Export  Blog Post elsewhere, but wanted to get thoughts on this from everyone else.

**Comment by kalwalt** [comment]
@joshuacox thank you for reporting this! Honestly i havenìt seen this warning, but maybe this can happens with a newest gatsby-cli version. I will test it.

**Comment by joshuacox** [comment]
Kind of botched the first couple of commits as I tried to merge from my changes on whatever gatsby new created (which apparently is an unrelated commit history from the original project).  The page query is still broken though, I need to travel today, but will continue to tinker with it.  I'd love to hear thoughts as well.

**Comment by joshuacox** [comment]
Kind of botched the first couple of commits as I tried to merge from my changes on whatever gatsby new created (which apparently is an unrelated commit history from the original project).  The page query is still broken though, I need to travel today, but will continue to tinker with it.
