### ISSUE TITLE
Change default language - defaultLangKey

### ISSUE THREAD

**Issue by venelinn** [kalwalt/gatsby-starter-i18n-bulma#94]
Changing default language in languages.js, doesn't work !
Setting `defaultLangKey: 'it'` keep redirecting to `/en`

Also replacing Italian lang with something else is extremely difficult. There should be a way to simplify this process!

Thanks !

**Comment by kalwalt** [comment]
> Changing default language in languages.js, doesn't work !
> Setting defaultLangKey: 'it' keep redirecting to /en

@venelinn thank you for reporting this! I will investigate it,

> Also replacing Italian lang with something else is extremely difficult. There should be a way to simplify this process!

Yes agree with you, because there are nested language definitions inside the GraphQL queries of the page templates. You have to make many changes and it is easy to miss something out of the boz that will break the 'system'. Probably the solution should be a new [gatsby-plugin-i18n](https://github.com/angeloocana/gatsby-plugin-i18n).

**Comment by kalwalt** [comment]
@venelinn I think the defaultLangKey is correct. But note that the gatsby-plugin-i18n has the `automatic browser-language detection and redirection` as described in the [Readme](https://github.com/angeloocana/gatsby-plugin-i18n/tree/master/packages/gatsby-plugin-i18n#starters)
the detection of the browser is accomplished by the [getBroserLanguage.js](https://github.com/angeloocana/gatsby-plugin-i18n/blob/master/packages/ptz-i18n/src/getBrowserLanguage.js) You can change your preferred language in you browser setting, in Chrome you can do under Settings > Languages > Order langs; Try to change the preferred lang and let me know. But the question raise: Why the defaultLangKey? maybe in case the browser has not set a preferred lang, or maybe there is a tech reason for the plugin mechanism.
Honestly i am not yet a super expert on this field... and on this plugin..

**Comment by venelinn** [comment]
@kalwalt  yes you are right ! Changing my `Default/preferred browser lang ` does the job. But with `defaultLangKey` I was expecting kind a `overwrite mode`!

Thanks again fro the help !

**Comment by kalwalt** [comment]
Nice! Thanks @venelinn  for trying my starter, if you have any other answer regarding the code or suggestions to improves the project, let me know. I am a self learner so i would like to have this kind of feedback by a  pro developer...
